default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: team_management_development
test:
  <<: *default
  database: team_management_test
production:
  <<: *default
  database: team_management_production
  username: team_management
  password: <%= ENV["TEAM_MANAGEMENT_DATABASE_PASSWORD"] %>